name: Release

on:
  workflow_dispatch: # allow a release to be triggered manually
    inputs:
      dry-run:
        description: 'Dry Run'
        required: true
        type: boolean
        default: false

jobs:
  build-rpms:
    name: Build RPMs
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    permissions:
      contents: write
      issues: read
      pull-requests: read
    if: ${{ !inputs.dry-run }}

  release:
    name: Release
    needs: [build-rpms]
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create GitHub release (cycjimmy/semantic-release-action)
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download Release Artifact
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      if: ${{ !inputs.dry-run }}
      with:
        merge-multiple: true
        pattern: built-rpms-*
        path: target/
    - name: Semantic Release
      uses: ./.github/semantic-release
      id: semantic_release
      with:
        dry-run: ${{ inputs.dry-run }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
