name: Release

on:
  workflow_dispatch: # allow a release to be triggered manually
    inputs:
      dry-run:
        description: 'Dry Run'
        required: true
        type: boolean
        default: false

jobs:
  get_release:
    name: Get Release
    uses: ./.github/workflows/semantic-release.yaml
    with:
      dry-run: true

  build-rpms:
    name: Build RPMs
    needs: [get_release]
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
    if: ${{ needs.get_release.outputs.new_release_published == 'true' && !inputs.dry-run }}
    with:
      release-version: ${{ needs.get_release.outputs.new_release_version }}

  release:
    name: Release
    needs: [get_release, build-rpms]
    if: ${{ needs.get_release.outputs.new_release_published == 'true' }}
    uses: ./.github/workflows/semantic-release.yaml
    with:
      dry-run: ${{ inputs.dry-run || false }}
      download-artifact-pattern: built-rpms-*
